# Uncomment the next line to define a global platform for your project
platform :ios, '9.0'

source 'https://github.com/CocoaPods/Specs.git'
#platform :ios, '8.0'
use_frameworks!

target 'SnapEye' do
  pod 'Cloudinary' , '~> 2.0'
end

